Improve folder's nameming and improve build script
Improving folder's naming from image and src-plantuml to img and src,
respectivily. Also build script was improved by making it more verbal
(it now tells if building a image was done succefully or not) and by
making it less hard coded with a for loop.

diff --git a/assets/build b/assets/build
--- a/assets/build
+++ b/assets/build
@@ -1,6 +1,9 @@
 #!/bin/sh
 
-java -jar plantuml.jar ./src-plantuml/class.txt 
-mv src-plantuml/class.png images/class.png
-java -jar plantuml.jar ./src-plantuml/relationship.txt
-mv src-plantuml/relationship.png images/relationship.png
+target=('class' 'get-post' 'login' 'relationship' 'show-user')
+
+for t in "${target[@]}"; do
+  echo "Building target: $t.txt"
+  java -jar ./plantuml.jar src/$t.txt -o ../img
+  [ $? -eq 0 ] && echo "Success building $t.txt" || echo "Error while building $t.txt"
+done
